### ISSUE TITLE
TPS freezes on enchant availability check + weird infinite enchants ignoring the global/set level cap

### ISSUE THREAD

**Issue by Desempregago** [auoeke/limitless#60]
Minecrat 1.17.1
Fabric 0.12.1 with API 0.41.3
Limitless 1.15.13

Video proof: https://streamable.com/b155si

**Comment by Desempregago** [comment]
I think I already know the cause... when setting custom "bookshelves", I forgot to add a comma to separate the two entries, breaking the config file, making every enchantment available as `MAX_INT` level

**Comment by Desempregago** [comment]
Closing it as I already have fixed it. Oversight on my end.

**Comment by yesn0t** [comment]
for some reason i have this bug too event though i didn't touch the config file, all enchants have initial max level of 2147483647 , and i looked at the config file and found this oddity :
```
      "whitelist": {
        "examplemod:example_block": 5.0
      },
      "blacklist": [
        "examplemod:example_block"
      ]
    },

```
i am not sure if that's a defined syntax in json but probably those brackets should be braces instead

**Comment by auoeke** [comment]
I don't remember looking deeply into this issue before but currently enchantment levels should be constrained by enchantment power as they are in vanilla Minecraft so this is either an incompatibility with mods or a bug that is absent from version 1.6.2. I presume that "∞" represents 2^31 - 1.

> for some reason i have this bug too event though i didn't touch the config file, all enchants have initial max level of 2147483647...

First: what are your limitless and Minecraft versions? 2^31 - 1 is the normal default limit; nobody should have to reduce it for a bug. If you have any mods that add enchantments, a list thereof (though in the case of a mod conflict most efficient is for the user to remove a half of their mods, test and repeat the process with the half of the mods wherewith the issue persists until the set of conflicting mods is found) and a screenshot of the generated enchantments after the lag spike with `enchantment.revealEnchantments` set to `true` would be helpful.

> i am not sure if that's a defined syntax in json but probably those brackets should be braces instead

The syntax is correct: `whitelist` uses braces because each block therein has to be mapped to a value (levels); `blacklist` uses brackets because it's just a list of blocks to exclude; no need for a value there.

> also i don't know how to reset the max levels to their default value from the config file, having to lookup vanilla and modded enchants in wikis for values seems not fun, and doing it from the config GUI is a long and tedious process

I think that those are your only options for now. I might add a subcommand `reset` to `/limitless` sometime.

**Comment by yesn0t** [comment]
thanks for the tips @auoeke , i will delete the config file, disable all other mods, create a new world and test the enchanting table, with and without revealEnchantments.

btw is it normal that the limitless-1.6.2.jar shows up as version 1.6.1 in the launcher as well as in ModMenu ?
i did download the 1.6.2 version and double checked but when i open the jar i find 
```
{
  "schemaVersion": 1,
  "id": "limitless",
  "version": "1.6.1",
```
in the fabric.mod.json

in my previous testing the lag was caused by those 2^31-1 level enchants, as everytime the enchanting GUI lagged, at least one enchant would show up to be level 2^31-1.
it didn't lag when the enchants were capped to V and when i manually set to a single digit limit or reset the max level of the specific enchant that was lagging it solves the problem momentarily until next enchant roll.

enchant related mods i was using are :
```
axesareweapons: Axes Are Weapons 1.5.1
basicshields: Basic Shields [Fabric] 1.2.1-1.18.1
betterthanmending: BetterThanMending 1.3.0
cenchants: Combat Enchants 1.10.3
fabricshieldlib: Fabric Shield Lib 1.4.5-1.18
limitless: limitless 1.6.1
popenchanttags: PopEnchantTagsResuscitated 1.1.0
```
and `fabric: Fabric API 0.45.0+1.18`
i kind of suspect a problem with either fabric api or the loader cause when i launched with 0.45.1, it either crashed immediately or corrupted/reset some of my mods' config files, so i had to revert to 0.45.0 and in that case the config files would still be wrecked ?
will try fabric 0.46.0 next time

**Comment by auoeke** [comment]
> btw is it normal that the limitless-1.6.2.jar shows up as version 1.6.1 in the launcher as well as in ModMenu ?

It's normal. I still don't know why the versions differ.

> i kind of suspect a problem with either fabric api or the loader cause when i launched with 0.45.1, it either crashed immediately or corrupted/reset some of my mods' config files, so i had to revert to 0.45.0 and in that case the config files would still be wrecked ?

Fabric API 0.45.1 works fine with limitless 1.6.2 for me. I don't think that you can undo the damage to your configuration files.
